language: R
sudo: false
cache: packages
before_install:
- openssl aes-256-cbc -K $encrypted_833b803026d5_key -iv $encrypted_833b803026d5_iv
  -in geoclient_app_creds.rds.enc -out tests/testthat/geoclient_app_creds.rds -d
